{
 "title": "Picture Frame",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum ( pictureframe_cpu_usage_percent{job=\"backend\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pictureframe_image_count{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data-dir Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pictureframe_data_dir_used_bytes{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used / Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pictureframe_memory_used_bytes{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, path) (\n  rate(http_requests_total[1m])\n)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(method, path, le) (rate(http_requests_duration_seconds_bucket{job=\"backend\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(method, path, le) (rate(http_requests_duration_seconds_bucket{job=\"backend\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(method, path, le) (rate(http_requests_duration_seconds_bucket{job=\"backend\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}