name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      crate:
        description: 'Crate to release'
        required: true
        type: choice
        options:
          - backend
          - display
          - hash_once
          - sdl_test

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ inputs.crate }} – ${{ matrix.platform }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        platform: [Linux-aarch64]
        include:
          - platform: Linux-aarch64
            runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache apt dependencies
        uses: actions/cache@v4
        with:
          path: /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Install SDL2 dependencies
        if: inputs.crate == 'sdl_test' || inputs.crate == 'display'
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install -y --no-install-recommends \
            libasound2-dev \
            libdbus-1-dev \
            libdrm-dev \
            libgbm-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libpulse-dev \
            libudev-dev \
            libwayland-dev \
            libx11-dev \
            libxcursor-dev \
            libxext-dev \
            libxi-dev \
            libxinerama-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libxss-dev \
            libxt-dev \
            libxxf86vm-dev \
            wayland-protocols \
            x11proto-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          target: aarch64-unknown-linux-gnu

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build ${{ inputs.crate }}
        run: |
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export PKG_CONFIG_ALLOW_CROSS=1
          export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          export RUSTFLAGS="-C target-cpu=generic -C link-arg=-Wl,--no-as-needed"
          cargo build --locked --release --target aarch64-unknown-linux-gnu --manifest-path crates/${{ inputs.crate }}/Cargo.toml \
            ${{ (inputs.crate == 'sdl_test' || inputs.crate == 'display') && '--features=sdl2/bundled' || '' }}
          cp crates/target/aarch64-unknown-linux-gnu/release/${{ inputs.crate }} ./${{ inputs.crate }}
          aarch64-linux-gnu-strip -s ./${{ inputs.crate }}
        env:
          RUST_BACKTRACE: full

      - name: Verify binary architecture
        run: |
          file ./${{ inputs.crate }}
          if ! file ./${{ inputs.crate }} | grep -q "ARM aarch64"; then
            echo "Error: Binary is not built for aarch64!"
            exit 1
          fi

      - name: Create Release for ${{ inputs.crate }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ inputs.crate }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: false
