name: rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "crates/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "crates/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SDL2 dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install -y --no-install-recommends libsdl2-dev

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "crates -> crates/target"
          key: ${{ matrix.rust }}
          save-if: ${{ github.event_name != 'pull_request' }}

      - name: Cargo build
        working-directory: ./crates
        run: cargo build --verbose

      - name: Cargo clippy
        working-directory: ./crates
        run: cargo clippy -- -D warnings

      - name: Cargo fmt
        working-directory: ./crates
        run: cargo fmt --all --check
